#!/bin/bash

if [ $EUID -ne 0 ]
  then echo 'Please run as sudo.'
  exit
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  echo 'Detecting operating system as Linux.'
  cd src/b++
  g++ -o b++ main.cpp
  mv b++ /usr/bin/
  alias b++=/usr/bin/b++
  echo "alias b++=/usr/bin/b++" >> ~/.bashrc
elif [[ "$OSTYPE" == "darwin"* ]]; then
  echo 'Detecting operating system as Mac.'
  # MAC OS CODE HERE
fi

echo "Install successful!"
