#!/bin/bash

if [ $EUID -ne 0 ]
  then echo 'Please run as sudo.'
  exit
fi

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  cd src/b++/Linux
  g++ -o b++ main.cpp
  mv b++ /usr/bin/
  alias b++=/usr/bin/b++
  echo "alias b++=/usr/bin/b++" >> ~/.bashrc
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # MAC OS CODE HERE
  
echo "Install successful!"
