#include <fstream>
#include <boost/algorithm/string/find.hpp>
#include <boost/algorithm/string.hpp>
#include <iostream>
#include <vector>
#include <iterator>
#include <cstddef>
#include <string>
#include <sstream>
#pragma once